### ISSUE TITLE
Developer Section in Readme

### ISSUE THREAD

**Issue by bastianhjaeger** [ydutertre/myvario#1]
Hi @ydutertre 

great work here. I installed the app on my Garmin and like it very much so far. 

I might want to contribute to the code base. Could you add a little section in the README and describe how I can work on the code base. Like 
- How do you build so far and on which platform?
- How to push the locally build app to my watch?

**Comment by ydutertre** [comment]
Hello Bastian!

Thanks for the feedback, glad you like the app!

So in terms of how to contribute, you need to follow the Garmin
instructions: https://developer.garmin.com/connect-iq/overview/

Basically:
- Visual Studio Code with Garmin plugin
- Can compile for your specific watch and put that in your watch app folder
to test, or create a Beta app on their app library

Cheers,

Yannick

**Comment by bastianhjaeger** [comment]
Great. I already did it. Looking ok so far. 
Maybe only a minor thing, but: 
If I built the app for my device and copied it to my watch, I was not able to access the settings menu vie the ConnectIQ on my android to e.g. set the LiveTrack account setting. What did I wrong here?

**Comment by ydutertre** [comment]
I think for that you need to register a Beta app on the app store!

**Comment by bastianhjaeger** [comment]
Thanks.
