### ISSUE TITLE
ACCELEROMETER_VARIANCE set in kalman incorrect

### ISSUE THREAD

**Issue by Samtropic** [ydutertre/myvario#10]
In the original arduino variometer code the value is either 0.3 when data is present or 0.6 when any.

```C++
#ifdef HAVE_ACCELEROMETER 
#define ACCELERATION_MEASURE_STANDARD_DEVIATION 0.3
#else
#define ACCELERATION_MEASURE_STANDARD_DEVIATION 0.6
```

**Comment by ydutertre** [comment]
Variance is the square of stdev, therefore the value of 0.36 is correct
