### ISSUE TITLE
Add a "Recommended/Review watches" section in the README

### ISSUE THREAD

**Issue by Skallwar** [ydutertre/myvario#3]
Hi,

Thanks for the app :tada:. 
I'm planning on buying a Garmin watch and I wonder which models are best suited for this app, in particuliar regarding the tone volume (I saw on one forum that the Fenix 7 series had poor beeper volume).

I think it would be useful to have a section on the readme (or a separate file) for feedback on how well each model is suited for this app (GPS accuracy, barometric sensitivity and response time, tone volume, vibration force, ...).

**Comment by ydutertre** [comment]
Thanks for the feedback and the request!
I have updated the [Readme ](https://github.com/ydutertre/myvario/blob/main/README.md) with my experience on various watches, in a new "Recommended watches" section.

**Comment by Skallwar** [comment]
Thanks you very much!
