### ISSUE TITLE
Firmware bug in 18.22 - app is not working

### ISSUE THREAD

**Issue by patrikniebur** [ydutertre/myvario#8]
Hi all, 

This took me a while to figure out so I thought I would share here to save someone's time. 
App is not working in 18.22 due to bug in firmware confirmed on [connectIQ forum](https://forums.garmin.com/developer/connect-iq/i/bug-reports/app-with-api-6-4-2-doesn-t-start-since-firmware-16-22-anymore)

**Comment by ydutertre** [comment]
Thanks Patrik!!

I've done the changes and uploaded a new version - hopefully it will get
properly released by Garmin soon.

Cheers!

Yannick

**Comment by patrikniebur** [comment]
Great, thanks a lot Yannick! I spent half day trying to figure out the error myself before getting response from Garmin. Now I wish I had posted here earlier!

**Comment by patrikniebur** [comment]
Release is out and I've tested on my forerunner 255, issue is resolved 🎉 Thanks again also for crediting in release notes

**Comment by ydutertre** [comment]
Awesome! Thanks again for raising it and thanks for the update!
